=== puneetsom/DashboardSRV/WebContent/WEB-INF/flex/amdocs-query-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by Adi Rabinovich (AT&T) -->
<!-- DTD generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) -->
<!-- Don't forget to use &gt; and &lt; for greater than and lower than, can be followed with equal like this  &lt;= -->
<!ELEMENT statement (#PCDATA)>
<!ATTLIST statement
	code CDATA #REQUIRED
	clientObject CDATA ""
	type CDATA "Default"
	debug (Yes | True | No)  "No"
	description CDATA ""
	paramsRequired (true | false)  "true"
>
<!-- "type" attribute is made dynamic, and it maps to Pool name, but has some recognized exceptions, like RefBean -->
<!ELEMENT sql ((statement+))>
<!ATTLIST sql
	type CDATA #REQUIRED 
>

=== puneetsom/DashboardSRV/WebContent/WEB-INF/flex/amdocs-query-SLV.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sql SYSTEM "amdocs-query-config.dtd">
<sql type="CdwSQL">

<statement code="employee_slv_all"><![CDATA[
	 SELECT EMPLOYEE_ID,
         EMP_FIRST_NAME,
         EMPLOYEE_SURNAME,
         EMPLOYEE_POSITION,
         EMPLOYEE.OFFICE_CODE,
         EMPLOYEE.OFFICE_TYPE,
         EMPLOYEE.SUPERVISOR_ID,
         EMPLOYEE.LAPTOP_IND
    FROM EMPLOYEE
ORDER BY UPPER (EMPLOYEE_SURNAME), UPPER (EMP_FIRST_NAME)
	]]></statement>
	
<statement code="employee_slv_active"><![CDATA[
	SELECT EMPLOYEE_ID,
         EMP_FIRST_NAME,
         EMPLOYEE_SURNAME,
         EMPLOYEE_POSITION,
         EMPLOYEE.OFFICE_CODE,
         EMPLOYEE.OFFICE_TYPE,
         EMPLOYEE.SUPERVISOR_ID,
         EMPLOYEE.EMPLOYEE_STATUS
    FROM EMPLOYEE
   WHERE EMPLOYEE.EMPLOYEE_STATUS = 0
ORDER BY UPPER (EMPLOYEE_SURNAME), UPPER (EMP_FIRST_NAME)
]]></statement>
	
<statement code="product_slv_all"><![CDATA[
 SELECT DISTINCT
         PRODUCT_ISSUE.PRODUCT_CODE,
         PRODUCT_ISSUE.PRODUCT_NAME,
         TO_CHAR (PRODUCT_ISSUE.ISSUE_DATE, 'mm/yyyy') PRODUCT_ISSUE_DATE,
         PRODUCT_ISSUE.PRODUCT_ISSUE_NUM
    FROM PRODUCT_ISSUE
   WHERE PRODUCT_ISSUE.PRODUCT_ISSUE_NUM in 
            (SELECT PRDISS2.PRODUCT_ISSUE_NUM 
               FROM PRODUCT_ISSUE PRDISS2
              WHERE PRDISS2.PRODUCT_CODE = PRODUCT_ISSUE.PRODUCT_CODE
                )
ORDER BY PRODUCT_NAME DESC
        ]]></statement>
        
<statement code="product_slv_period"><![CDATA[
SELECT DISTINCT
         PRODUCT_ISSUE.PRODUCT_CODE,
         PRODUCT_ISSUE.PRODUCT_NAME,
         TO_CHAR (PRODUCT_ISSUE.ISSUE_DATE, 'mm/yyyy') PRODUCT_ISSUE_DATE,
         PRODUCT_ISSUE.PRODUCT_ISSUE_NUM
    FROM PRODUCT_ISSUE
   WHERE PRODUCT_ISSUE.PRODUCT_ISSUE_NUM in 
            (SELECT PRDISS2.PRODUCT_ISSUE_NUM 
               FROM PRODUCT_ISSUE PRDISS2
              WHERE PRDISS2.PRODUCT_CODE = PRODUCT_ISSUE.PRODUCT_CODE
             	and to_char(PRDISS2.ISSUE_DATE, 'YYYY') > (to_char(sysdate, 'YYYY')-3)
                )
ORDER BY PRODUCT_NAME DESC
]]></statement>     
  
<statement code="canvass_slv_all"><![CDATA[
  SELECT CANVASS_CODE,
         CANVASS_ISSUE_NUM,
         CANVASS_NAME,
         CANVASS_ISSUE_MNTH,
         CANVASS_ISSUE_YEAR,
         DECODE (
            (CANVASS.CANVASS_ISSUE_MNTH || '/' || CANVASS.CANVASS_ISSUE_YEAR),
            '/', ' ',
            (CANVASS.CANVASS_ISSUE_MNTH || '/' || CANVASS.CANVASS_ISSUE_YEAR))
            CANVASS_ISSUE_DATE
    FROM CANVASS
ORDER BY CANVASS_NAME, CANVASS_ISSUE_NUM DESC
 ]]></statement>  	
 
 <statement code="canvass_slv_period"><![CDATA[
 SELECT CANVASS_CODE,
         CANVASS_ISSUE_NUM,
         CANVASS_NAME,
         CANVASS_ISSUE_MNTH,
         CANVASS_ISSUE_YEAR,
         DECODE (
            (CANVASS.CANVASS_ISSUE_MNTH || '/' || CANVASS.CANVASS_ISSUE_YEAR),
            '/', ' ',
            (CANVASS.CANVASS_ISSUE_MNTH || '/' || CANVASS.CANVASS_ISSUE_YEAR))
            CANVASS_ISSUE_DATE
    FROM CANVASS
    where canvass_issue_year > (to_char(sysdate, 'YYYY')-3) 
ORDER BY CANVASS_NAME, CANVASS_ISSUE_NUM DESC]]></statement>


<statement code="CBPB_rep_slv"><![CDATA[
select value employee_id
     , display
     , emp_first_name
     , employee_surname
     , login_name
from   (select   a.value
               , a.display
               , a.employee_surname
               , a.emp_first_name
               , a.login_name
               , row_number()
                       over(partition by value
                            order by     instr(lower(a.search), lower({search}))
                                       , a.display) rnum
        from     employee_ac a
        where    lower(a.search) like lower('%'||{search}||'%')
        and      (a.value in (select distinct rep_id from CSO_CMSN_EXTRACT_CA where cmsn_handle_status in ('N') and last_version_ind = 'Y')
               or a.value in (select distinct rep_id from CMSN_CBPB_MV))
        order by instr(lower(a.search), lower({search}))
               , a.display)
where  rnum = 1
and    rownum <= 50
]]></statement>

</sql>

=== puneetsom/DashboardSRV/WebContent/WEB-INF/flex/amdocs-query-10B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sql SYSTEM "amdocs-query-config.dtd">
<sql type="CdwSQL">
	<statement code="D10BMarketQuery" clientObject="10B">
		select distinct market_id value , market_name label from market_name_ca order by 2
	</statement>
	
	<statement code="D10BProductQuery" clientObject="10B">
select ' ALL' label , ' ALL' value from dual union all
select p.product_name label , m.product_code value    
from market_ca m, all_prod_issue p                   
where m.product_code = p.product_code
and m.market_id = {market}              
and p.bots_issue_ind = 'Y'                          
	</statement>
	
	<statement code="D10BMediaMgrQuery" clientObject="10B">
 select media_mgr_id value, max(media_mgr_surname|| ', ' || media_mgr_first_nm) label,
max(media_mgr_surname) media_mgr_surname
from d10b_acct_detail_smy_ca
WHERE  MARKET_ID =  {market}                                                                      
AND ( 'emptyParam' = {product}                                                                   
or PRODUCT_CODE =  {product}  or {product} = ' ALL')   
group by media_mgr_id
order by 3                             
	</statement>
	
	<statement code="D10BVerticalSegmentQuery" clientObject="10B">
select vertical_name label, vertical_id value from vertical_name_ca union all select ' ALL',0 from dual 
order by 1
	</statement>
	
	<statement code="D10BAccntSmyGridQuery" clientObject="10B">
SELECT                                                                                               
A.MARKET_NAME MARKET,
A.PRODUCT_NAME PRODUCT_NAME,                                                                                
A.CHANNEL_CODE CHANNEL,                                                                              
A.MEDIA_MGR_ID || ' - ' ||  TRIM(A.MEDIA_MGR_FIRST_NM )|| ' ' || TRIM(A.MEDIA_MGR_SURNAME) MEDIA_MGR,
A.CUSTOMER_ID CUSTOMER_ID,                                                                           
A.CUSTOMER_NAME CUSTOMER_NAME,                                                                       
A.VERTICAL_NAME SEGMENT,                                                                             
A.TOT_NISD_AMT TOT_NISD_AMT,                                                                         
A.PRINT_REV_AMT PRINT_REV_AMT,                                                                       
A.IYP_REV_AMT IYP_REV_AMT,                                                                           
A.PREV_TOT_NISD_AMT PREV_TOT_NISD_AMT,                                                               
A.PREV_PRINT_REV_AMT PREV_PRINT_REV_AMT,                                                             
A.PREV_IYP_REV_AMT PREV_IYP_REV_AMT,                                                                 
A.ALL_NISD_AMT ALL_NISD_AMT,                                                                         
A.ALL_PRINT_NISD_AMT ALL_PRINT_NISD_AMT,                                                             
A.ALL_IYP_NISD_AMT ALL_IYP_NISD_AMT,                                                                 
A.ALL_PREV_NISD_AMT ALL_PREV_NISD_AMT,                                                               
A.ALL_PREV_PRINT_AMT ALL_PREV_PRINT_AMT,                                                             
A.ALL_PREV_IYP_AMT ALL_PREV_IYP_AMT                                                                  
FROM                                                                                                 
D10B_ACCT_DETAIL_SMY_CA A                                                                            
WHERE ( 'emptyParam' = {market}                                                                    
or A.MARKET_ID =  {market} )                                                                       
AND ( 'emptyParam' = {product}                                                                   
or A.PRODUCT_CODE =  {product}  or {product} = ' ALL')                                                                 
AND ( 'emptyParam' = {mediaMgr}                                                                    
or A.MEDIA_MGR_ID =  {mediaMgr} )                                                                  
AND( 0  = {verticalSegment}                                                                     
or A.VERTICAL_ID = {verticalSegment} )                                                                
ORDER BY                                                                                             
MARKET,                                                                                              
CHANNEL,                                                                                             
MEDIA_MGR,                                                                                           
CUSTOMER_ID        
</statement>

<statement code="D10BTrckSmyGridQuery" clientObject="10B">
SELECT
A.CUSTOMER_ID CUSTOMER_ID,
A.CUSTOMER_NAME CUSTOMER_NAME,
mn.market_name market_name,
A.VERTICAL_NAME VERTICAL_NAME,
a.product_code product_code,
a.product_name product_name,
A.MEDIA_MGR_ID|| ' - ' || MEDIA_MGR_FIRST_NM || ' ' || MEDIA_MGR_SURNAME MEDIA_MGR,
A.AIN_PROGRAM_ID || ' / ' || AIN_PROGRAM_AGE AIN_PROGRAM,
A.AIN_PROGRAM_ID ain_program_id,
AIN_PROGRAM_AGE ain_program_age,
A.PROGRAM_TYPE PROGRAM_TYPE,
A.GAP_IND GAP_IND,
A.GUARANTEE_NUM_CALLS GUARANTEE_NUM_CALLS,
A.NUM_CLICKS NUM_CLICKS,
A.NUM_IMPRESSIONS NUM_IMPRESSIONS,
A.ROI ROI,
A.ROI_SOURCE ROI_SOURCE,
A.NUM_YP_CALLS NUM_YP_CALLS,
A.NUM_WP_CALLS NUM_WP_CALLS,
A.NUM_IYP_CALLS NUM_IYP_CALLS,
A.TOTAL_CALLS TOTAL_CALLS,
A.PCT_CALLS_BUSINESS PCT_CALLS_BUSINESS,
A.NUM_POTENTIAL_CALLS NUM_POTENTIAL_CALLS,
A.POT_REV_PER_MO POT_REV_PER_MO,
A.TOT_AD_COST_PER_MO TOT_AD_COST_PER_MO,
A.NET_REV NET_REV,
A.CONV_RATE CONV_RATE,
A.NUM_CONV_CALLS NUM_CONV_CALLS,
A.NUM_CLICK_YPCOM NUM_CLICK_YPCOM ,
A.NUM_IMP_YPCOM NUM_IMP_YPCOM,
A.NUM_CLICK_YPCON NUM_CLICK_YPCON,
A.NUM_IMP_YPCON NUM_IMP_YPCON,
A.NUM_CLICK_YODA NUM_CLICK_YODA,
A.NUM_IMP_YODA NUM_IMP_YODA,
A.NUM_411_TEXT NUM_411_TEXT,
a.source_code source_code,
a.AVG_VT_MO_CALLS,
a.AVG_PPC_MO_CALLS,
a.AVG_PPC_MO_CHARGE,
a.AVG_CALLS_PER_SALE,
a.AVG_PROFIT_PER_SALE,
a.AVG_CUS_WORTH
FROM D10B_TRACKING_SMY_CA  A
, market_ca m ,
(select distinct market_id , market_name from market_name_ca) mn
WHERE A.product_code = m.product_code
and m.market_id = mn.market_id
AND  ( 'emptyParam' = {market}
or m.market_id =  {market} ) 
AND ( 'emptyParam' = {product}
or A.PRODUCT_CODE =  {product} or {product} = ' ALL' ) 
AND ( 'emptyParam' = {mediaMgr}
or A.MEDIA_MGR_ID =  {mediaMgr} ) 
AND( 0 = {verticalSegment}
or A.VERTICAL_ID = {verticalSegment})
order by
a.CUSTOMER_ID, a.PRODUCT_CODE, a.VERTICAL_ID, a.AIN_PROGRAM_ID 
</statement>

<statement code="D10BTrckSmyDtlsGridQuery" clientObject="10B">
SELECT 
A.AIN_PROGRAM_ID	,
(case WHEN A.SOURCE_CODE = 'CORB' THEN 'Southeast'
 WHEN A.SOURCE_CODE = 'CORM' THEN 'Midwest'
 WHEN A.SOURCE_CODE = 'CORS' THEN 'Southwest'
 ELSE 'West' END) source_code ,
A.AIN_PROGRAM_AGE       ,
A.REGION_CODE           ,
C.DECODE_DISPLAY REGION ,
A.PROGRAM_TYPE          ,
A.CUSTOMER_ID           ,
A.LISTED_NAME           ,
A.PRODUCT_CODE          ,
A.PRODUCT_NAME          ,
A.PRODUCT_ISSUE         ,
A.STATE_ABBREVIATION    ,
A.ISSUE_DATE            ,
A.ITEM_BOTS_AMT         ,
A.ITEM_NISD_AMT         ,
A.GUARANTEE_NUM_CALLS   ,
A.HEADING_CODE          ,
A.HEADING_NAME          ,
A.UDAC_CODE             ,
A.COLOR_CODE            ,
A.MULT_ITEM_IND         ,
A.COMPETITIVE_IND       ,
A.AVG_CALLS             ,
A.ITEM_CPC              ,
A.NUM_ACTIVE_MO         ,
A.NUM_CTN               ,
A.CALLS_MO_1            ,
A.CALLS_MO_2            ,
A.CALLS_MO_3            ,
A.CALLS_MO_4            ,
A.CALLS_MO_5            ,
A.CALLS_MO_6            ,
A.CALLS_MO_7            ,
A.CALLS_MO_8            ,
A.CALLS_MO_9            ,
A.CALLS_MO_10           ,
A.CALLS_MO_11           ,
A.CALLS_MO_12           ,
A.CTN1                  ,
A.CTN2                  ,
A.CTN3                  ,
A.CTN4                  ,
A.CTN5                  ,
A.CTN6                  ,
A.CTN7                  ,
A.CTN8                  ,
A.CTN9                  ,
A.CTN10                 ,
A.CTN11                 ,
A.CTN12                 ,
A.CTN13                 ,
A.CTN14                 ,
A.CTN15                 ,
A.TERM1                 ,
A.TERM2                 ,
A.TERM3                 ,
A.TERM4                 ,
A.TERM5                 ,
A.TERM6                 ,
A.TERM7                 ,
A.TERM8                 ,
A.TERM9                 ,
A.TERM10                ,
A.TERM11                ,
A.TERM12                ,
A.TERM13                ,
A.TERM14                ,
A.TERM15
FROM D10B_TRACKING_DTL_SMY_CA A, ALL_PROD_ISSUE B , DOMAIN_DECODES C
WHERE ( 'emptyParam' = {ainProgramId}
or A.AIN_PROGRAM_ID =  {ainProgramId} ) 
AND ( 'emptyParam' = {ainProgramAge}
or A.AIN_PROGRAM_AGE =  {ainProgramAge} ) 
AND ( 'emptyParam' = {sourceCode}
or A.SOURCE_CODE =  {sourceCode} ) 
AND( 'emptyParam' = {customerId}
or A.CUSTOMER_ID = {customerId} )
AND ( 'emptyParam' = {product}
or A.PRODUCT_CODE =  {product} or {product} = ' ALL' ) 
AND A.PRODUCT_CODE          = B.PRODUCT_CODE 
AND B.BOTS_ISSUE_IND         = 'Y'
AND A.region_code=C.code_value(+)
AND C.domain_code='REGIONCODE'
order by 
a.CUSTOMER_ID, a.PRODUCT_CODE, a.PRODUCT_ISSUE, a.HEADING_CODE, a.UDAC_CODE
</statement>
                                                                                  

</sql>

=== puneetsom/DashboardSRV/WebContent/WEB-INF/flex/amdocs-query-GRID.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sql SYSTEM "amdocs-query-config.dtd">
<sql type="CdwSQL">

  <!--  ea_grid_favorite -->
  
  <!-- TODO Add join for CREATE_OPER_NAME -->
  <statement code="GRID_selectFavorites"><![CDATA[
select   f.favorite_id
       , f.view_id
       , f.grid_id
       , f.favorite_name
       , f.locked_column_count
       , f.show_footer_ind
       , f.public_ind
       , f.create_date
       , f.create_oper_id
       , trim(e.emp_first_name||' '||e.employee_surname) create_oper_name
       , c.column_id
       , c.column_order
       , c.column_width
       , c.sort_order
       , c.descending_ind
       , c.column_type
       , c.data_field
       , c.expression
from     ea_grid_favorite f
         join 
         (select favorite_id
               , column_id
               , column_order
               , column_width
               , sort_order
               , descending_ind
               , 'N' column_type
               , null data_field
               , null expression
          from   ea_grid_fav_cols 
          union all
          select favorite_id
               , column_id
               , column_order
               , null column_width
               , null sort_order
               , null descending_ind
               , 'G' column_type
               , null data_field
               , null expression
          from   ea_grid_fav_grp_cols
          union all
          select favorite_id
               , null
               , null
               , null
               , null
               , null
               , null
               , data_field
               , expression
          from   ea_grid_fav_filter_cols
         ) c
           on f.favorite_id = c.favorite_id
         left outer join employee e
           on f.create_oper_id = e.employee_id
where    f.view_id = ?
and      f.grid_id = ?
and      (f.public_ind = 'Y' or f.create_oper_id = ?)
order by (case when public_ind = 'N' then 0 else 1 end)
       , favorite_name
       , f.favorite_id
       , f.grid_id
       , c.column_order
       , c.column_id
       , c.data_field
  ]]></statement>

  <!-- TODO Add join for CREATE_OPER_NAME -->  
  <statement code="GRID_selectFavorite"><![CDATA[
select   *
from     ea_grid_favorite
where    favorite_id = ?
  ]]></statement>
  
  <statement code="GRID_insertFavorite"><![CDATA[
insert into ea_grid_favorite
      (favorite_id 
     , view_id 
     , grid_id 
     , favorite_name
     , locked_column_count 
     , show_footer_ind 
     , public_ind 
     , update_date 
     , update_oper_id 
     , create_date 
     , create_oper_id)
values (?, ?, ?, ?, ?
       ,?, ?, SYSDATE, ?, SYSDATE, ?)
  ]]></statement>
  
  <statement code="GRID_updateFavorite"><![CDATA[
update ea_grid_favorite
set    view_id = ?
     , grid_id = ?
     , favorite_name = ?
     , locked_column_count = ?
     , show_footer_ind = ?
     , public_ind = ?
     , update_date = SYSDATE
     , update_oper_id = ?
where  favorite_id = ?
  ]]></statement>
  
  <statement code="GRID_lookupFavoriteId"><![CDATA[
select favorite_id
from   ea_grid_favorite
where  view_id = ?
and    grid_id = ?
and    favorite_name = ?
and    create_oper_id = ?
  ]]></statement>
  
  <statement code="GRID_selectNewFavoriteId"><![CDATA[
select ea_grid_favorite_seq.nextval 
from   dual
  ]]></statement>
  
  <statement code="GRID_deleteFavorite"><![CDATA[
delete from ea_grid_favorite
where  favorite_id = ?
and    create_oper_id = ? 
  ]]></statement>
  
  
  
  <!--  ea_grid_fav_cols -->
  <statement code="GRID_selectFavoriteColumns"><![CDATA[
select   *
from     ea_grid_fav_cols
where    favorite_id = ?
order by column_order
  ]]></statement>
  
  <statement code="GRID_insertFavoriteColumn"><![CDATA[
insert into ea_grid_fav_cols
       (favorite_id
      , column_id
      , column_order
      , column_width
      , sort_order
      , descending_ind)
values (?, ?, ?, ?, 0, 'N')
  ]]></statement>
  
  <statement code="GRID_deleteFavoriteColumns"><![CDATA[
delete from ea_grid_fav_cols 
where  favorite_id = ?
  ]]></statement>
  
  <statement code="GRID_updateFavoriteSortColumn"><![CDATA[
update ea_grid_fav_cols 
set    sort_order = ? 
     , descending_ind = ? 
where  favorite_id = ? 
and    column_id = ?
  ]]></statement>
  
  
  
  <!--  ea_grid_fav_grp_cols -->
  <statement code="GRID_selectFavoriteGroupColumns"><![CDATA[
select   *
from     ea_grid_fav_grp_cols
where    favorite_id = ?
order by column_order
  ]]></statement>
  
  <statement code="GRID_insertFavoriteGroupColumn"><![CDATA[
insert into ea_grid_fav_grp_cols
       (favorite_id
      , column_id
      , column_order)
values (?, ?, ?)
  ]]></statement>
  
  <statement code="GRID_deleteFavoriteGroupColumns"><![CDATA[
delete from ea_grid_fav_grp_cols
where  favorite_id = ?
  ]]></statement>
  
  
  
  <!--  ea_grid_fav_filter_cols -->
  <statement code="GRID_selectFavoriteFilterColumns"><![CDATA[
select * 
from   ea_grid_fav_filter_cols
where  favorite_id = ? 
  ]]></statement>
  
  <statement code="GRID_insertFavoriteFilterColumn"><![CDATA[
insert into ea_grid_fav_filter_cols
       (favorite_id
      , data_field
      , expression)
values (?, ?, ?)
  ]]></statement>
  
  <statement code="GRID_deleteFavoriteFilterColumn"><![CDATA[
delete from ea_grid_fav_filter_cols
where  favorite_id = ? 
  ]]></statement>
  
</sql>
