=== puneetsom/DashboardSRV/WebContent/WEB-INF/flex/amdocs-xml-loader-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Don't forget to use &gt; and &lt; for greater than and lower than, can be followed with equal like this  &lt;= -->
<!ELEMENT xml-file (#PCDATA)>
<!ATTLIST xml-file
	code CDATA #REQUIRED
    location CDATA #REQUIRED
    context CDATA ""
	clientObject CDATA ""
	debug (Yes | True | No)  "No"
	description CDATA ""
>
<!-- "type" attribute is made dynamic, and it maps to Pool name, but has some recognized exceptions, like RefBean -->
<!ELEMENT xml-files ((xml-file+))>
<!ATTLIST xml-files
	type CDATA #REQUIRED 
>

=== puneetsom/DashboardSRV/WebContent/WEB-INF/flex/amdocs-xml-loader-IypSalesOps.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml-files SYSTEM "amdocs-xml-loader-config.dtd">
<xml-files type="IypSalesOps-XML">

   <xml-file code="ServiceManagerContractsSummary" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Summary/Contracts.xml" />
   <xml-file code="ServiceManagerContractsTotal" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Summary/ContractsTotal.xml" />
   <xml-file code="ServiceManagerContractsDetails" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Details/Contracts-details.xml" />

   <xml-file code="ServiceManagerPendingItemsSummary" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Summary/PendingItems.xml" />
   <xml-file code="ServiceManagerPendingItemsTotal" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Summary/PendingItemsTotal.xml" />
   <xml-file code="ServiceManagerPendingItemsDetails" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Details/PendingItems-details.xml" />

   <xml-file code="ServiceManagerInProgressItemsSummary" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Summary/InProgressItems.xml" />
   <xml-file code="ServiceManagerInProgressItemsTotal" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Summary/InProgressItemsTotal.xml" />
   <xml-file code="ServiceManagerInProgressItemsDetails" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Details/InProgressItems-details.xml" />

   <xml-file code="ServiceManagerCompletedItemsSummary" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Summary/CompletedItems.xml" />
   <xml-file code="ServiceManagerCompletedItemsTotal" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Summary/CompletedItemsTotal.xml" />
   <xml-file code="ServiceManagerCompletedItemsDetails" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Details/CompletedItems-details.xml" />

   <xml-file code="ServiceManagerQueryItemsSummary" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Summary/QueryItems.xml" />
   <xml-file code="ServiceManagerQueryItemsTotal" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Summary/QueryItemsTotal.xml" />
   <xml-file code="ServiceManagerQueryItemsDetails" location="http://cafrfd1y5wdev01.itsdo.sbc.com:8080/data/ServiceManager/Details/QueryItems-details.xml" />



   <xml-file code="IypCycleTimeLastYear" location="http://executive-advisor.web.att.com/data/IypCycleTime/cycle-time-last-year-stats-{type}.xml" clientObject="YearlyIypCycleTime" />
   <xml-file code="IypCycleTimeMonthlyByUmg" location="http://executive-advisor.web.att.com/data/IypCycleTime/UMG/{yyyy-dd}-{type}-monthly-cycle-time.xml " clientObject="MonthlyIypCycleTime" />
   <xml-file code="IypCycleTimeMonthlyByUdacGroup" location="http://executive-advisor.web.att.com/data/IypCycleTime/UDAC-GROUP/{yyyy-dd}-{udacGroup}-monthly-cycle-time.xml " clientObject="MonthlyIypCycleTime" />

</xml-files>

=== puneetsom/DashboardSRV/WebContent/WEB-INF/flex/amdocs-xml-loader-SalesKpi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml-files SYSTEM "amdocs-xml-loader-config.dtd">
<xml-files type="SalesKpi-XML">
   <xml-file code="ReportsMetadata" context="com.amdocs.dashboard.mobile.reports" location="WEB-INF\xml\Reports.xml" clientObject="" />
   <xml-file code="AssetsMetadata" context="com.amdocs.dashboard.mobile.assets" location="WEB-INF\xml\Assets.xml" clientObject="" />
   
   <xml-file code="ProdDefectsMetadata" context="com.amdocs.dashboard.mobile.report" location="WEB-INF\xml\ProdDefects.xml" clientObject="" />
   <xml-file code="ProdDefectsColumns" context="com.amdocs.dashboard.mobile.grid" location="WEB-INF\xml\ProdDefectsColumns.xml" clientObject="" />
   
   <xml-file code="SalesKpiReportMetadata" context="com.amdocs.dashboard.mobile.kpiReport" location="WEB-INF\xml\SalesKpiReport.xml" clientObject="" />
   <xml-file code="SalesKpiCategoryColumns" context="com.amdocs.dashboard.mobile.grid" location="WEB-INF\xml\SalesKpiCategoryColumns.xml" clientObject="" />
   <xml-file code="SalesKpiCustomerColumns" context="com.amdocs.dashboard.mobile.grid" location="WEB-INF\xml\SalesKpiCustomerColumns.xml" clientObject="" />
 
   <xml-file code="SalesKpiTrendChartMetadata" context="com.amdocs.dashboard.mobile.xyChart" location="WEB-INF\xml\SalesKpiTrendChart.xml" clientObject="" />
   <xml-file code="SalesKpiYOYChartMetadata" context="com.amdocs.dashboard.mobile.xyChart" location="WEB-INF\xml\SalesKpiYOYChart.xml" clientObject="" />
   
   <xml-file code="RevReportMetadata" context="com.amdocs.dashboard.mobile.kpiReport" location="WEB-INF\xml\RevReport.xml" clientObject="" />
   <xml-file code="RevReportCategoryColumns" context="com.amdocs.dashboard.mobile.grid" location="WEB-INF\xml\RevReportCategoryColumns.xml" clientObject="" />
   <xml-file code="RevReportCustomerColumns" context="com.amdocs.dashboard.mobile.grid" location="WEB-INF\xml\RevReportCustomerColumns.xml" clientObject="" />
   
   <xml-file code="RevReportTrendChartMetadata" context="com.amdocs.dashboard.mobile.xyChart" location="WEB-INF\xml\RevReportTrendChart.xml" clientObject="" />
   <xml-file code="RevReportYOYChartMetadata" context="com.amdocs.dashboard.mobile.xyChart" location="WEB-INF\xml\RevReportYOYChart.xml" clientObject="" />
   
   <xml-file code="ABRKpiReportMetadata" context="com.amdocs.dashboard.mobile.kpiReport" location="WEB-INF\xml\ABRKpiReport.xml" clientObject="" />
   <xml-file code="ABRKpiCategoryColumns" context="com.amdocs.dashboard.mobile.grid" location="WEB-INF\xml\ABRKpiCategoryColumns.xml" clientObject="" /> 
   <xml-file code="ABRKpiTrendChartMetadata" context="com.amdocs.dashboard.mobile.xyChart" location="WEB-INF\xml\ABRKpiTrendChart.xml" clientObject="" />
   <xml-file code="ABRKpiYOYChartMetadata" context="com.amdocs.dashboard.mobile.xyChart" location="WEB-INF\xml\ABRKpiYOYChart.xml" clientObject="" />
   <xml-file code="ABRKpiDetailColumns" context="com.amdocs.dashboard.mobile.grid" location="WEB-INF\xml\ABRKpiDetailColumns.xml" clientObject="" />
   
</xml-files>
