=== puneetsom/DashboardSRV/WebContent/WEB-INF/xsd/CustomDataGrid.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		   xmlns:tn="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid"
           xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
           jxb:version="2.0">

  <xs:complexType name="CustomDataGrid">
    <xs:sequence>
      <xs:element ref="tn:Column" maxOccurs="unbounded">
		<xs:annotation>
			<xs:appinfo>
				<jxb:property name="columns" />
			</xs:appinfo>
		</xs:annotation>
      </xs:element>
      <xs:element ref="tn:GroupedColumns" minOccurs="0" maxOccurs="1">
		<xs:annotation>
			<xs:appinfo>
				<jxb:property name="groupedColumns" />
			</xs:appinfo>
		</xs:annotation>
      </xs:element>
      <!--<xs:element ref="tn:ColumnFilters" minOccurs="0" maxOccurs="1"/>-->
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="title" type="xs:string" />
    <xs:attribute name="version" type="xs:int" />
    <xs:attribute name="allowLockedColumnChange" type="xs:boolean" />
    <xs:attribute name="allowShowFooterChange" type="xs:boolean" />
    <xs:attribute name="lockedColumnCount" type="xs:int" />
    <xs:attribute name="showFooter" type="xs:boolean" />
    <xs:attribute name="showFilters" type="xs:boolean" />

	<xs:attribute name="defaultItemRenderer" default="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
						<!-- suggested values -->
						<xs:enumeration value="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer" />
						<xs:enumeration value="mx.controls.advancedDataGridClasses.AdvancedDataGridItemRenderer" />
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="defaultItemEditor" default="com.amdocs.dashboard.customDataGrid.CustomDataGridItemEditor">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
						<!-- suggested values -->
						<xs:enumeration value="com.amdocs.dashboard.customDataGrid.CustomDataGridItemEditor" />						
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
  </xs:complexType> 
  
  <xs:element name="CustomDataGrid" type="tn:CustomDataGrid" />
  
  <xs:complexType name="GroupedColumns">
  	<xs:sequence>
      <xs:element ref="tn:Column" maxOccurs="unbounded"/>
    </xs:sequence> 
    <xs:attribute name="label" type="xs:string" />
    <xs:attribute name="description" type="xs:string" />
    <xs:attribute name="exportOnly" type="xs:boolean" default="true" />
  </xs:complexType>
  
  <xs:element name="GroupedColumns" type="tn:GroupedColumns" />
  
  <xs:complexType name="Column">
    
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="dataField" type="xs:string" />
    <xs:attribute name="dataTipField" type="xs:string" />
    
    <xs:attribute name="headerLabel" type="xs:string" />
    <xs:attribute name="headerWordWrap" type="xs:boolean" />
    
    <xs:attribute name="type" default="string">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="string"/>
          <xs:enumeration value="checkbox"/>
          <xs:enumeration value="currency"/>
          <xs:enumeration value="date"/>
          <xs:enumeration value="datetime"/>
          <xs:enumeration value="datestring"/>
          <xs:enumeration value="number"/>
          <xs:enumeration value="percent"/>
          <xs:enumeration value="phone"/>
          <xs:enumeration value="zipcode"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="locked" type="xs:boolean" />    
    <xs:attribute name="key" type="xs:boolean" />
    
    <xs:attribute name="securityProfile">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
					Comma delimited list of security profiles needed
					to see this column
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
	<xs:attribute name="itemRenderer" default="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
						<!-- suggested values -->
						<xs:enumeration value="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer" />
						<xs:enumeration value="mx.controls.advancedDataGridClasses.AdvancedDataGridItemRenderer" />
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
    <xs:attribute name="itemRendererSecurityProfile">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
					Comma delimited list of security profiles needed 
					to use the itemRenderer for this column
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

    <xs:attribute name="itemEditor" default="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
						<!-- suggested values -->
						<xs:enumeration value="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer" />
						<xs:enumeration value="mx.controls.CheckBox" />
						<xs:enumeration value="mx.controls.ComboBox" />
						<xs:enumeration value="mx.controls.DateField" />
						<xs:enumeration value="mx.controls.TextArea" />
						<xs:enumeration value="mx.controls.TextInput" />
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="itemEditorSecurityProfile">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
					Comma delimited list of security profiles needed 
					to use the itemEditor for this column
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
	<xs:attribute name="useItemEditorAsItemRenderer">
		<xs:simpleType>
			<xs:restriction base="xs:boolean">
				<xs:annotation>
					<xs:documentation>
					If true, itemEditor will be used as itemRenderer.  
					This is useful for cases when you want to specific 
					an input element (like checkbox or dropdown list) 
					to always display on the screen and not require the 
					user to click on the cell
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
	
	<xs:attribute name="headerItemRenderer" default="mx.controls.advancedDataGridClasses.AdvancedDataGridHeaderRenderer">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
						<!-- suggested values -->
						<xs:enumeration value="com.amdocs.dashboard.customDataGrid.renderers.CustomDataGridHeaderFilterRenderer" />
						<xs:enumeration value="mx.controls.advancedDataGridClasses.AdvancedDataGridHeaderRenderer" />
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
    
    <xs:attribute name="click" type="xs:string" />
    
    <xs:attribute name="visible" default="true">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="true"/>
          <xs:enumeration value="false"/>
          <xs:enumeration value="always"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="footerType">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="currency"/>
          <xs:enumeration value="number"/>
          <xs:enumeration value="percent"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute> 
    <xs:attribute name="footerFunction">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="avg"/>
          <xs:enumeration value="count"/>
          <xs:enumeration value="sum"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="footerLabel" type="xs:string" />
    <xs:attribute name="currencySymbol" type="xs:string" default="$" />
    <xs:attribute name="decimalSeparator" type="xs:string" default="," />
    <xs:attribute name="digitTypes" type="xs:string" />
    <xs:attribute name="errorText" type="xs:string" />
    <xs:attribute name="fractionalDigits" type="xs:int" default="-1" />
    <xs:attribute name="groupingPattern" type="xs:string" />
    <xs:attribute name="groupingSeparator" type="xs:string" default="," />
    <xs:attribute name="leadingZero" type="xs:boolean" />
    <xs:attribute name="negativeCurrencyFormat" type="xs:int" />
    <xs:attribute name="negativeSymbol" type="xs:string" />
    <xs:attribute name="positiveCurrencyFormat" type="xs:int" />
    <xs:attribute name="trailingZeros" type="xs:boolean" />
    <xs:attribute name="useGrouping" type="xs:boolean" default="true" />
    <xs:attribute name="includeInExport" type="xs:boolean" default="true" />
    <xs:attribute name="dateTimePattern" type="xs:string" />
    
    <!-- NumericStepper specific attributes -->
    <xs:attribute name="minimum" type="xs:decimal" />
    <xs:attribute name="maximum" type="xs:decimal" />
    <xs:attribute name="maxChars" type="xs:int" />
    <xs:attribute name="stepSize" type="xs:decimal" />
    <xs:attribute name="snapInterval" type="xs:decimal" />
    
        
    <xs:attribute name="textAlign">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="center"/>
          <xs:enumeration value="left"/>
          <xs:enumeration value="right"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  	<xs:attribute name="truncateToFit">
		<xs:simpleType>
			<xs:restriction base="xs:boolean">
				<xs:annotation>
					<xs:documentation>
					If true, then text longer than the width of the column
					will be truncated with ellipse (...).  Set to false for columns
					with very large values (like multi-line comments) so they render
					more quickly.
					See https://issues.apache.org/jira/browse/FLEX-23962
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
    
  	<xs:attribute name="width" type="xs:int" />
  	<xs:attribute name="widthInChars" type="xs:int" />
  	<xs:attribute name="heightInLines" type="xs:int" />
  	<xs:attribute name="editable" type="xs:boolean" />
  	<xs:attribute name="size" type="xs:int" />
  	<xs:attribute name="required" type="xs:boolean" />
    <xs:attribute name="domainCode" type="xs:string" />
    <xs:attribute name="formField" type="xs:string" />
  	<xs:attribute name="formType" default="Label">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="CheckBox"/>
          <xs:enumeration value="ComboBox"/>
          <xs:enumeration value="DateField"/>
          <xs:enumeration value="DropDownList"/>
          <xs:enumeration value="Employee"/>
          <xs:enumeration value="Label"/>
          <xs:enumeration value="NumericStepper"/>
          <xs:enumeration value="RadioButton"/>
          <xs:enumeration value="SLVFormElement"/>
          <xs:enumeration value="TextInput"/>
          <xs:enumeration value="TextArea"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="formGroup" type="xs:string" />
  	<xs:attribute name="filterable" type="xs:boolean" />
  	
    <xs:attribute name="sortable">
		<xs:simpleType>
			<xs:restriction base="xs:boolean">
				<xs:annotation>
					<xs:documentation>
					Defines specifies whether column is sortable for async data grid
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
    <xs:attribute name="relatedColumns">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
					Comma delimited list of dataFields of other columns to select
					whem selecting columns from backend (mainly for item renderers)
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
    <xs:attribute name="relatedGroupColumns">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
					Comma delimited list of dataFields of other columns to select
					whem selecting columns from backend (mainly for item renderers)
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
  </xs:complexType>
  
  <xs:element name="Column" type="tn:Column" />
  
</xs:schema>

=== puneetsom/DashboardSRV/WebContent/WEB-INF/xml/SalesKpiCustomerColumns.xml
<?xml version="1.0" encoding="UTF-8"?>
<CustomDataGrid xmlns="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xsi:schemaLocation="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid ../xsd/CustomDataGrid.xsd"
                lockedColumnCount="2"
                title="Customers"
                version="3">
                
  <!-- <Column id="prdYear" dataField="prd_year" textAlign="center" visible="false" /> -->
  <Column id="customerId" dataField="customer_id" headerLabel="Customer Id" visible="true" />
  <Column id="customerName" dataField="customer_name" headerLabel="Customer Name" visible="true" />
  
  <Column id="regionName" dataField="region_name" headerLabel="Region" visible="true" />
  <Column id="productCode" dataField="product_code" headerLabel="Product Code" visible="true" />
  <Column id="prdYear" dataField="prd_year" headerLabel="Product Year" visible="true" />
  <Column id="productType" dataField="product_type" headerLabel="Product Type" textAlign="center" visible="true" />
  <Column id="canvassYear" dataField="cvs_year" headerLabel="Campaign Year" visible="true" />
  
  <Column id="channelCode" dataField="channel_code" headerLabel="Channel" textAlign="center" visible="true" />
  <Column id="prospectCode" dataField="prospect_code" headerLabel="Prospect" textAlign="center" visible="true" />
  <Column id="poolInd" dataField="pool_ind" headerLabel="Pool" textAlign="center" visible="true" />
  <Column id="handledInd" dataField="handled_ind" headerLabel="Handled?" textAlign="center" visible="true" />
  
  <Column id="asgnAmt" dataField="asgn_amt" headerLabel="Assigned Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="hndlAmt" dataField="hndl_amt" headerLabel="Handled Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="soldAmt" dataField="sold_amt" headerLabel="Sold Amt" visible="true" type="currency" fractionalDigits="0" />

  <Column id="renewalAmt" dataField="renewal_amt" headerLabel="Renewal Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="increaseAmt" dataField="increase_amt" headerLabel="Increase Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="decreaseAmt" dataField="decrease_amt" headerLabel="Decrease Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="cancelAmt" dataField="cancel_amt" headerLabel="Cancel Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="oblAmt" dataField="obl_amt" headerLabel="OBL Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="newAmt" dataField="new_amt" headerLabel="New Amt" visible="true" type="currency" fractionalDigits="0" />

  <Column id="boostHdlAmt" dataField="bst_hndl_amt" headerLabel="Boost Handled Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="boostSoldAmt" dataField="bst_sold_amt" headerLabel="Boost Sold Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="disconnectAmt" dataField="discon_amt" headerLabel="Disconnect Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="delinquentAmt" dataField="delinq_amt" headerLabel="Delinquent Amt" visible="true" type="currency" fractionalDigits="0" />

  <Column id="canvassCode" dataField="canvass_code" headerLabel="Campaign Code" visible="false" />
  <Column id="repName" dataField="rep_name" headerLabel="Rep" visible="false" />
  <Column id="salesMgrName" dataField="sales_mgr_name" headerLabel="Sales Mgr" visible="false" />
  <Column id="gmName" dataField="gm_name" headerLabel="GM" visible="false" />

  
</CustomDataGrid>

=== puneetsom/DashboardSRV/WebContent/WEB-INF/xml/RevReportCustomerColumns.xml
<?xml version="1.0" encoding="UTF-8"?>
<CustomDataGrid xmlns="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xsi:schemaLocation="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid ../xsd/CustomDataGrid.xsd"
                lockedColumnCount="2"
                title="Customers"
                version="1">
                
  <!-- <Column id="prdYear" dataField="prd_year" textAlign="center" visible="false" /> -->
  <Column id="customerId" dataField="customer_id" headerLabel="Customer Id" visible="true" />
  <Column id="customerName" dataField="customer_name" headerLabel="Customer Name" visible="true" />
  
  <!-- 
  <Column id="regionName" dataField="region_name" headerLabel="Region" visible="true" />
  <Column id="productCode" dataField="product_code" headerLabel="Product Code" visible="true" />
  <Column id="prdYear" dataField="prd_year" headerLabel="Product Year" visible="true" />
  <Column id="productType" dataField="product_type" headerLabel="Product Type" textAlign="center" visible="true" />
  <Column id="canvassYear" dataField="cvs_year" headerLabel="Campaign Year" visible="true" />
   -->
  <Column id="channelCode" dataField="channel_code" headerLabel="Channel" textAlign="center" visible="true" />
  <!-- 
  <Column id="prospectCode" dataField="prospect_code" headerLabel="Prospect" textAlign="center" visible="true" />
  <Column id="poolInd" dataField="pool_ind" headerLabel="Pool" textAlign="center" visible="true" />
  <Column id="handledInd" dataField="handled_ind" headerLabel="Handled?" textAlign="center" visible="true" />
  
  <Column id="asgnAmt" dataField="asgn_amt" headerLabel="Assigned Amt" visible="true" type="currency" fractionalDigits="0" />
   -->
  <Column id="totAmt" dataField="rc" headerLabel="Revenue" visible="true" type="currency" fractionalDigits="0" />
  <Column id="hndlAmt" dataField="handled_rc" headerLabel="Handled Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="soldAmt" dataField="sold_rc" headerLabel="Sold Amt" visible="true" type="currency" fractionalDigits="0" />

  <Column id="renewalAmt" dataField="renewal_rc" headerLabel="Renewal Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="increaseAmt" dataField="increase_rc" headerLabel="Increase Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="decreaseAmt" dataField="decrease_rc" headerLabel="Decrease Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="cancelAmt" dataField="cancel_rc" headerLabel="Cancel Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="oblAmt" dataField="obl_rc" headerLabel="OBL Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="newAmt" dataField="new_rc" headerLabel="New Amt" visible="true" type="currency" fractionalDigits="0" />

<!-- 
  <Column id="boostHdlAmt" dataField="bst_hndl_amt" headerLabel="Boost Handled Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="boostSoldAmt" dataField="bst_sold_amt" headerLabel="Boost Sold Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="disconnectAmt" dataField="discon_amt" headerLabel="Disconnect Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="delinquentAmt" dataField="delinq_amt" headerLabel="Delinquent Amt" visible="true" type="currency" fractionalDigits="0" />
 -->
  <Column id="campaignCode" dataField="campaign_code" headerLabel="Campaign Code" visible="false" />
  <Column id="repName" dataField="rep_name" headerLabel="Rep" visible="false" />
  <Column id="salesMgrName" dataField="sales_mgr_name" headerLabel="Sales Mgr" visible="false" />
  <!-- <Column id="gmName" dataField="gm_name" headerLabel="GM" visible="false" /> -->

  
</CustomDataGrid>

=== puneetsom/DashboardSRV/WebContent/WEB-INF/xml/SalesKpiCategoryColumns.xml
<?xml version="1.0" encoding="UTF-8"?>
<CustomDataGrid xmlns="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xsi:schemaLocation="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid ../xsd/CustomDataGrid.xsd"
                lockedColumnCount="1"
                version="1">
                
  <!-- <Column id="prdYear" dataField="prd_year" textAlign="center" visible="false" /> -->
  <Column id="catName" dataField="cat_name" headerLabel="Category" visible="true" />
  
  <Column id="ypAsgnAmt" dataField="yp_asgn_amt" headerLabel="Print Assigned Amt" visible="false" type="currency" fractionalDigits="0" />
  <Column id="ypHndlAmt" dataField="yp_hndl_amt" headerLabel="Print Handled Amt" visible="false" type="currency" fractionalDigits="0" />
  <Column id="ypSoldAmt" dataField="yp_sold_amt" headerLabel="Print Sold Amt" visible="false" type="currency" fractionalDigits="0" />
  <Column id="ypObj" dataField="yp_obj" headerLabel="Print Objective" visible="false" type="currency" fractionalDigits="0" />

  <Column id="iypAsgnAmt" dataField="iyp_asgn_amt" headerLabel="Internet Assigned Amt" visible="false" type="currency" fractionalDigits="0" />
  <Column id="iypHndlAmt" dataField="iyp_hndl_amt" headerLabel="Internet Handled Amt" visible="false" type="currency" fractionalDigits="0" />
  <Column id="iypSoldAmt" dataField="iyp_sold_amt" headerLabel="Internet Sold Amt" visible="false" type="currency" fractionalDigits="0" />
  <Column id="iypObj" dataField="iyp_obj" headerLabel="Internet Objective" visible="false" type="currency" fractionalDigits="0" />

  <Column id="asgnCnt" dataField="asgn_cnt" headerLabel="# Assigned" visible="true" type="number" />
  <Column id="asgnAmt" dataField="asgn_amt" headerLabel="Total Assigned Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="hndlCnt" dataField="hndl_cnt" headerLabel="# Handled" visible="true" type="number" />
  <Column id="hndlAmt" dataField="hndl_amt" headerLabel="Total Handled Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="soldCnt" dataField="sold_cnt" headerLabel="# Sold" visible="true" type="number" />
  <Column id="soldAmt" dataField="sold_amt" headerLabel="Total Sold Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="obj" dataField="obj" headerLabel="Total Objective" visible="true" type="currency" fractionalDigits="0" />

  <Column id="renewalCnt" dataField="renewal_cnt" headerLabel="# Renewal" visible="true" type="number" />
  <Column id="renewalAmt" dataField="renewal_amt" headerLabel="Renewal Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="increaseCnt" dataField="increase_cnt" headerLabel="# Increase" visible="true" type="number" />
  <Column id="increaseAmt" dataField="increase_amt" headerLabel="Increase Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="decreaseCnt" dataField="decrease_cnt" headerLabel="# Decrease" visible="true" type="number" />
  <Column id="decreaseAmt" dataField="decrease_amt" headerLabel="Decrease Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="cancelCnt" dataField="cancel_cnt" headerLabel="# Cancel" visible="true" type="number" />
  <Column id="cancelAmt" dataField="cancel_amt" headerLabel="Cancel Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="oblCnt" dataField="obl_cnt" headerLabel="# OBL" visible="true" type="number" />
  <Column id="oblAmt" dataField="obl_amt" headerLabel="OBL Amt" visible="true" type="currency" fractionalDigits="0" />
  <Column id="newCnt" dataField="new_cnt" headerLabel="# New" visible="true" type="number" />
  <Column id="newAmt" dataField="new_amt" headerLabel="New Amt" visible="true" type="currency" fractionalDigits="0" />
  
</CustomDataGrid>

=== puneetsom/DashboardSRV/WebContent/WEB-INF/xml/ABRKpiCategoryColumns.xml
<?xml version="1.0" encoding="UTF-8"?>
<CustomDataGrid xmlns="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xsi:schemaLocation="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid ../xsd/CustomDataGrid.xsd"
                lockedColumnCount="1"
                version="1">
  
  <Column id="catName" dataField="cat_name" headerLabel="Category" visible="true" />
  
  <Column id="iypHndlAmt" dataField="iyp_hndl_amt" headerLabel="SVC" visible="true" type="currency" fractionalDigits="0" />
  <Column id="iypHndlObj" dataField="iyp_hndl_obj" headerLabel="Prev SRV" visible="true" type="currency" fractionalDigits="0" />
  <Column id="iypHndlChgAmt" dataField="iyp_hndl_chg_amt" headerLabel="SVC Change" visible="false" type="currency" fractionalDigits="0" />
  <Column id="iypHndlChgPct" dataField="iyp_hndl_chg_pct" headerLabel="SVC Change %" visible="true" type="percent" fractionalDigits="1" />
  
  <Column id="iypIncreaseAmt" dataField="iyp_increase_amt" headerLabel="ITA" visible="true" type="currency" fractionalDigits="0" />
  <Column id="iypIncreaseObj" dataField="iyp_increase_obj" headerLabel="Prev ITA" visible="true" type="currency" fractionalDigits="0" />
  <Column id="iypIncreaseChgAmt" dataField="iyp_increase_chg_amt" headerLabel="ITA Change" visible="false" type="currency" fractionalDigits="0" />
  <Column id="iypIncreaseChgPct" dataField="iyp_increase_chg_pct" headerLabel="ITA Change %" visible="true" type="percent" fractionalDigits="1" />
  
  <Column id="iypOblAmt" dataField="iyp_obl_amt" headerLabel="OBL" visible="true" type="currency" fractionalDigits="0" />
  <Column id="iypOblObj" dataField="iyp_obl_obj" headerLabel="Prev OBL" visible="true" type="currency" fractionalDigits="0" />
  <Column id="iypOblChgAmt" dataField="iyp_obl_chg_amt" headerLabel="OBL Change" visible="false" type="currency" fractionalDigits="0" />
  <Column id="iypOblChgPct" dataField="iyp_obl_chg_pct" headerLabel="OBL Change %" visible="true" type="percent" fractionalDigits="1" />
  
  <Column id="iypNewAmt" dataField="iyp_new_amt" headerLabel="New" visible="true" type="currency" fractionalDigits="0" />
  <Column id="iypNewObj" dataField="iyp_new_obj" headerLabel="Prev New" visible="true" type="currency" fractionalDigits="0" />
  <Column id="iypNewChgAmt" dataField="iyp_new_chg_amt" headerLabel="New Change" visible="false" type="currency" fractionalDigits="0" />
  <Column id="iypNewChgPct" dataField="iyp_new_chg_pct" headerLabel="New Change %" visible="true" type="percent" fractionalDigits="1" />
  
  <Column id="iypSoldAmt" dataField="iyp_sold_amt" headerLabel="Sold" visible="true" type="currency" fractionalDigits="0" />
  <Column id="iypSoldObj" dataField="iyp_sold_obj" headerLabel="Prev Sold" visible="true" type="currency" fractionalDigits="0" />
  <Column id="iypSoldChgAmt" dataField="iyp_sold_chg_amt" headerLabel="Sold Change" visible="false" type="currency" fractionalDigits="0" />
  <Column id="iypSoldChgPct" dataField="iyp_sold_chg_pct" headerLabel="Sold Change %" visible="true" type="percent" fractionalDigits="1" />
  
  <Column id="iypNetAmt" dataField="iyp_net_amt" headerLabel="Net" visible="true" type="currency" fractionalDigits="0" />
  <Column id="iypNetObj" dataField="iyp_net_obj" headerLabel="Prev Net" visible="true" type="currency" fractionalDigits="0" />
  <Column id="iypNetChgAmt" dataField="iyp_net_chg_amt" headerLabel="Net Change" visible="false" type="currency" fractionalDigits="0" />
  <Column id="iypNetChgPct" dataField="iyp_net_chg_pct" headerLabel="Net Change %" visible="true" type="percent" fractionalDigits="1" />
  
  <Column id="prevIypNetSrvPct" dataField="prev_iyp_net_srv_pct" headerLabel="Prev Net %" visible="true" type="percent" fractionalDigits="1" />
  <Column id="iypNetSrvPct" dataField="iyp_net_srv_pct" headerLabel="Net %" visible="true" type="percent" fractionalDigits="1" />
  <Column id="iypNetPctGrowth" dataField="iyp_net_pct_growth" headerLabel="Net % Growth" visible="true" type="percent" fractionalDigits="1" />
  
</CustomDataGrid>
