=== puneetsom/DashboardSRV/WebContent/WEB-INF/xsd/CustomDataGrid.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		   xmlns:tn="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid"
           xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
           jxb:version="2.0">

  <xs:complexType name="CustomDataGrid">
    <xs:sequence>
      <xs:element ref="tn:Column" maxOccurs="unbounded">
		<xs:annotation>
			<xs:appinfo>
				<jxb:property name="columns" />
			</xs:appinfo>
		</xs:annotation>
      </xs:element>
      <xs:element ref="tn:GroupedColumns" minOccurs="0" maxOccurs="1">
		<xs:annotation>
			<xs:appinfo>
				<jxb:property name="groupedColumns" />
			</xs:appinfo>
		</xs:annotation>
      </xs:element>
      <!--<xs:element ref="tn:ColumnFilters" minOccurs="0" maxOccurs="1"/>-->
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="title" type="xs:string" />
    <xs:attribute name="version" type="xs:int" />
    <xs:attribute name="allowLockedColumnChange" type="xs:boolean" />
    <xs:attribute name="allowShowFooterChange" type="xs:boolean" />
    <xs:attribute name="lockedColumnCount" type="xs:int" />
    <xs:attribute name="showFooter" type="xs:boolean" />
    <xs:attribute name="showFilters" type="xs:boolean" />

	<xs:attribute name="defaultItemRenderer" default="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
						<!-- suggested values -->
						<xs:enumeration value="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer" />
						<xs:enumeration value="mx.controls.advancedDataGridClasses.AdvancedDataGridItemRenderer" />
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="defaultItemEditor" default="com.amdocs.dashboard.customDataGrid.CustomDataGridItemEditor">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
						<!-- suggested values -->
						<xs:enumeration value="com.amdocs.dashboard.customDataGrid.CustomDataGridItemEditor" />						
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
  </xs:complexType> 
  
  <xs:element name="CustomDataGrid" type="tn:CustomDataGrid" />
  
  <xs:complexType name="GroupedColumns">
  	<xs:sequence>
      <xs:element ref="tn:Column" maxOccurs="unbounded"/>
    </xs:sequence> 
    <xs:attribute name="label" type="xs:string" />
    <xs:attribute name="description" type="xs:string" />
    <xs:attribute name="exportOnly" type="xs:boolean" default="true" />
  </xs:complexType>
  
  <xs:element name="GroupedColumns" type="tn:GroupedColumns" />
  
  <xs:complexType name="Column">
    
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="dataField" type="xs:string" />
    <xs:attribute name="dataTipField" type="xs:string" />
    
    <xs:attribute name="headerLabel" type="xs:string" />
    <xs:attribute name="headerWordWrap" type="xs:boolean" />
    
    <xs:attribute name="type" default="string">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="string"/>
          <xs:enumeration value="checkbox"/>
          <xs:enumeration value="currency"/>
          <xs:enumeration value="date"/>
          <xs:enumeration value="datetime"/>
          <xs:enumeration value="datestring"/>
          <xs:enumeration value="number"/>
          <xs:enumeration value="percent"/>
          <xs:enumeration value="phone"/>
          <xs:enumeration value="zipcode"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="locked" type="xs:boolean" />    
    <xs:attribute name="key" type="xs:boolean" />
    
    <xs:attribute name="securityProfile">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
					Comma delimited list of security profiles needed
					to see this column
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
	<xs:attribute name="itemRenderer" default="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
						<!-- suggested values -->
						<xs:enumeration value="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer" />
						<xs:enumeration value="mx.controls.advancedDataGridClasses.AdvancedDataGridItemRenderer" />
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
    <xs:attribute name="itemRendererSecurityProfile">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
					Comma delimited list of security profiles needed 
					to use the itemRenderer for this column
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

    <xs:attribute name="itemEditor" default="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
						<!-- suggested values -->
						<xs:enumeration value="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer" />
						<xs:enumeration value="mx.controls.CheckBox" />
						<xs:enumeration value="mx.controls.ComboBox" />
						<xs:enumeration value="mx.controls.DateField" />
						<xs:enumeration value="mx.controls.TextArea" />
						<xs:enumeration value="mx.controls.TextInput" />
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="itemEditorSecurityProfile">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
					Comma delimited list of security profiles needed 
					to use the itemEditor for this column
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
	<xs:attribute name="useItemEditorAsItemRenderer">
		<xs:simpleType>
			<xs:restriction base="xs:boolean">
				<xs:annotation>
					<xs:documentation>
					If true, itemEditor will be used as itemRenderer.  
					This is useful for cases when you want to specific 
					an input element (like checkbox or dropdown list) 
					to always display on the screen and not require the 
					user to click on the cell
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
	
	<xs:attribute name="headerItemRenderer" default="mx.controls.advancedDataGridClasses.AdvancedDataGridHeaderRenderer">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
						<!-- suggested values -->
						<xs:enumeration value="com.amdocs.dashboard.customDataGrid.renderers.CustomDataGridHeaderFilterRenderer" />
						<xs:enumeration value="mx.controls.advancedDataGridClasses.AdvancedDataGridHeaderRenderer" />
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
    
    <xs:attribute name="click" type="xs:string" />
    
    <xs:attribute name="visible" default="true">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="true"/>
          <xs:enumeration value="false"/>
          <xs:enumeration value="always"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="footerType">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="currency"/>
          <xs:enumeration value="number"/>
          <xs:enumeration value="percent"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute> 
    <xs:attribute name="footerFunction">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="avg"/>
          <xs:enumeration value="count"/>
          <xs:enumeration value="sum"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="footerLabel" type="xs:string" />
    <xs:attribute name="currencySymbol" type="xs:string" default="$" />
    <xs:attribute name="decimalSeparator" type="xs:string" default="," />
    <xs:attribute name="digitTypes" type="xs:string" />
    <xs:attribute name="errorText" type="xs:string" />
    <xs:attribute name="fractionalDigits" type="xs:int" default="-1" />
    <xs:attribute name="groupingPattern" type="xs:string" />
    <xs:attribute name="groupingSeparator" type="xs:string" default="," />
    <xs:attribute name="leadingZero" type="xs:boolean" />
    <xs:attribute name="negativeCurrencyFormat" type="xs:int" />
    <xs:attribute name="negativeSymbol" type="xs:string" />
    <xs:attribute name="positiveCurrencyFormat" type="xs:int" />
    <xs:attribute name="trailingZeros" type="xs:boolean" />
    <xs:attribute name="useGrouping" type="xs:boolean" default="true" />
    <xs:attribute name="includeInExport" type="xs:boolean" default="true" />
    <xs:attribute name="dateTimePattern" type="xs:string" />
    
    <!-- NumericStepper specific attributes -->
    <xs:attribute name="minimum" type="xs:decimal" />
    <xs:attribute name="maximum" type="xs:decimal" />
    <xs:attribute name="maxChars" type="xs:int" />
    <xs:attribute name="stepSize" type="xs:decimal" />
    <xs:attribute name="snapInterval" type="xs:decimal" />
    
        
    <xs:attribute name="textAlign">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="center"/>
          <xs:enumeration value="left"/>
          <xs:enumeration value="right"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  	<xs:attribute name="truncateToFit">
		<xs:simpleType>
			<xs:restriction base="xs:boolean">
				<xs:annotation>
					<xs:documentation>
					If true, then text longer than the width of the column
					will be truncated with ellipse (...).  Set to false for columns
					with very large values (like multi-line comments) so they render
					more quickly.
					See https://issues.apache.org/jira/browse/FLEX-23962
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
    
  	<xs:attribute name="width" type="xs:int" />
  	<xs:attribute name="widthInChars" type="xs:int" />
  	<xs:attribute name="heightInLines" type="xs:int" />
  	<xs:attribute name="editable" type="xs:boolean" />
  	<xs:attribute name="size" type="xs:int" />
  	<xs:attribute name="required" type="xs:boolean" />
    <xs:attribute name="domainCode" type="xs:string" />
    <xs:attribute name="formField" type="xs:string" />
  	<xs:attribute name="formType" default="Label">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="CheckBox"/>
          <xs:enumeration value="ComboBox"/>
          <xs:enumeration value="DateField"/>
          <xs:enumeration value="DropDownList"/>
          <xs:enumeration value="Employee"/>
          <xs:enumeration value="Label"/>
          <xs:enumeration value="NumericStepper"/>
          <xs:enumeration value="RadioButton"/>
          <xs:enumeration value="SLVFormElement"/>
          <xs:enumeration value="TextInput"/>
          <xs:enumeration value="TextArea"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="formGroup" type="xs:string" />
  	<xs:attribute name="filterable" type="xs:boolean" />
  	
    <xs:attribute name="sortable">
		<xs:simpleType>
			<xs:restriction base="xs:boolean">
				<xs:annotation>
					<xs:documentation>
					Defines specifies whether column is sortable for async data grid
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
    <xs:attribute name="relatedColumns">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
					Comma delimited list of dataFields of other columns to select
					whem selecting columns from backend (mainly for item renderers)
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
    <xs:attribute name="relatedGroupColumns">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:annotation>
					<xs:documentation>
					Comma delimited list of dataFields of other columns to select
					whem selecting columns from backend (mainly for item renderers)
					</xs:documentation>
				</xs:annotation>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
  </xs:complexType>
  
  <xs:element name="Column" type="tn:Column" />
  
</xs:schema>

=== puneetsom/DashboardSRV/WebContent/WEB-INF/xml/ProdDefectsColumns.xml
<?xml version="1.0" encoding="UTF-8"?>
<CustomDataGrid xmlns="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xsi:schemaLocation="http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid ../xsd/CustomDataGrid.xsd"
                lockedColumnCount="1"
                showFilters="true"
                version="1">
	   		
	<Column id="defectId" headerLabel="Defect ID" dataField="defect_id" visible="true" type="number" useGrouping="false" fractionalDigits="0" width="75" />
    <Column id="sts" headerLabel="Status"  dataField="status" visible="true" width="80"   />        
    <Column id="authType" headerLabel="Auth Type" dataField="auth_type" visible="false" />
    <Column id="authDt" headerLabel="Auth Date" type="datestring" textAlign="center" dataField="auth_date" visible="false" />
    <Column id="authBy" headerLabel="Auth By" dataField="auth_by" visible="false" />
    <Column id="authArea" headerLabel="Auth Area" dataField="auth_area" visible="false" />
    <Column id="itBaOwner" headerLabel="IT BA Owner" dataField="it_ba_owner" visible="true" />
    <Column id="amdocsBaOwner" headerLabel="Amdocs BA Owner" dataField="amdocs_ba_owner" visible="true" />
    <Column id="defectSrc" headerLabel="Defect Source" dataField="defect_source" visible="true" width="95" />
    <Column id="severity" headerLabel="Severity"   dataField="severity" visible="true"  />
    <Column id="plannedClosingVersion" headerLabel="Planned Closing Version"  textAlign="center" dataField="planned_closing_version" visible="true" width="85" />
    <Column id="remedyTicket" headerLabel="Remedy Ticket" dataField="remedy_ticket"  visible="true" width="85" />
	<Column id="changeCallNumber" headerLabel="Change Call Number" dataField="change_call_number" visible="true" width="70" />
	<Column id="detOnDate" headerLabel="Detected on Date" dataField="det_on_date" type="datestring" textAlign="center" visible="true" width="90" />
	<Column id="detInVersion" headerLabel="Detect In Version" textAlign="center" dataField="det_in_version"  visible="true" width="100" />
	<Column id="businessArea" headerLabel="Business Area" dataField="business_area"  visible="true" width="170" /> 
	<Column id="summary" headerLabel="Summary" headerWordWrap="false" dataField="summary" visible="true" width="400" /> 
	<Column id="responsibleApplication" headerLabel="Responsible Application" dataField="responsible_application"  visible="true" width="120" /> 
    <Column id="desc" headerLabel="Description" dataField="description" visible="true" width="400" />
    <Column id="bus_validated" headerLabel="Bus. Validated?" textAlign="center" dataField="bus_validated" visible="true" /> 
    <Column id="validationType" headerLabel="Validation Type" dataField="validation_type"  visible="true" /> 
    <Column id="busImpacts" headerLabel="Business Impacts" dataField="bus_impacts"  visible="true" width="150" /> 
    <Column id="affectedUsers" headerLabel="Affected Users" dataField="affected_users"  visible="true" width="150" /> 
    <Column id="workMode" headerLabel="Work Mode" dataField="work_mode" visible="true" width="190" /> 
    <Column id="includeInAdvisor" headerLabel="Include In Advisor?" textAlign="center" dataField="include_in_advisor"  visible="true" /> 
    <Column id="advisorResolution" headerLabel="Advisor Resolution" dataField="advisor_resolution"  visible="true" width="400" /> 
    <Column id="defectType" headerLabel="Defect Type" dataField="defect_type"  visible="true" /> 
    <Column id="region" headerLabel="Region" dataField="region"  visible="true" />           
    <Column id="stUatqcDefect" headerLabel="ST/UATQC Defect #" dataField="st_uat_qc_defect"  visible="true" />          
    <Column id="priority" headerLabel="Priority" dataField="priority"  visible="true" />  
    <Column id="assignedTo" headerLabel="Assigned To" dataField="amdocs_assign_to" />
    <Column id="responsibleSubAppl" headerLabel="Responsible Sub Application" dataField="responsible_sub_app" visible="true" />
    <Column id="closingDt" headerLabel="Closing Date" dataField="closing_date" type="datestring" textAlign="center" visible="true" />
    <Column id="plannedDeployedDt" headerLabel="Planned Deployed Date" dataField="planned_deployed_date" type="datestring" textAlign="center" visible="true" />
    <Column id="closingVersion" headerLabel="Closing Version" dataField="closing_version" textAlign="center" visible="true" />  
   
</CustomDataGrid>
