=== puneetsom/DashboardSRV/WebContent/WEB-INF/xsd/XYChart.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.amdocs.com/dashboard/mobile/XYChart"
           xmlns:tn="http://www.amdocs.com/dashboard/mobile/XYChart"
           elementFormDefault="qualified"
           xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
           jxb:version="2.0">
  
	<xs:simpleType name="chartType">
      	<xs:annotation>
			<xs:documentation>line and area are only valid for lineSeries. clustered and stacked are only valid for columnSeries</xs:documentation>
		</xs:annotation>
    	<xs:restriction base="xs:string">
      		<xs:enumeration value="line" />
      		<xs:enumeration value="area" />
      		<xs:enumeration value="clustered" />
      		<xs:enumeration value="stacked" />
    	</xs:restriction>
	</xs:simpleType>

    <xs:simpleType name="fieldType">
    	<xs:restriction base="xs:string">
      		<xs:enumeration value="string" />
      		<xs:enumeration value="number" />
      		<xs:enumeration value="currency" />
      		<xs:enumeration value="percent" />
    	</xs:restriction>
	</xs:simpleType>
  
    <xs:simpleType name="positionType">
    	<xs:restriction base="xs:string">
      		<xs:enumeration value="top" />
      		<xs:enumeration value="bottom" />
      		<xs:enumeration value="left" />
      		<xs:enumeration value="right" />
    	</xs:restriction>
	</xs:simpleType>
	
  	<xs:simpleType name="ServiceParamTypeAttr">
    	<xs:restriction base="xs:string">
      		<xs:enumeration value="string" />
      		<xs:enumeration value="number" />
    	</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="ServiceParam">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="type" type="tn:ServiceParamTypeAttr" />
		<xs:attribute name="required" type="xs:boolean" default="true" />
	</xs:complexType>
	
	<xs:complexType name="ServiceElement">
		<xs:sequence>
			<xs:element type="tn:ServiceParam" name="Param" minOccurs="0" maxOccurs="unbounded">	
      			<xs:annotation>
        			<xs:appinfo>
          				<jxb:property name="params" />
        			</xs:appinfo>
      			</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="serviceCode" type="xs:string" />
		<xs:attribute name="cacheLife" type="xs:int">
			<xs:annotation>
				<xs:documentation>Number of seconds data from service should be cached on client</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="seriesElement">
		<xs:attribute type="xs:string" name="id" />
		<xs:attribute type="xs:string" name="displayName" />
		<xs:attribute type="xs:string" name="yField"/>
		<xs:attribute type="xs:string" name="fillColor" use="optional">
			<xs:annotation>
				<xs:documentation>Fill color is only used for a lineSeries of type
					area</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:float" name="fillAlpha" use="optional" />
	</xs:complexType>

  	<xs:complexType name="columnSeriesElement">
  		<xs:complexContent>
  			<xs:extension base="tn:seriesElement" />
  		</xs:complexContent>
	</xs:complexType>
 
	<xs:complexType name="seriesSetElement">
		<xs:annotation>
			<xs:documentation>
				Column and Line charts can be plotted on a single chart, but do not use
				the Set and Series elements of one type.
				
				For example, you can mix columnSet and lineSeries, or you can mix
				columnSeries and lineSeries, but you cannot mix lineSet and lineSeries.
				
				Sets are used for more than one series. Series is used when you only have a 
				single series.
					</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="columnSet" type="tn:columnSetElement" minOccurs="0" maxOccurs="1" />
			<xs:element name="columnSeries" type="tn:columnSeriesElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="lineSet" type="tn:lineSetElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="lineSeries" type="tn:lineSeriesElement" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="type" type="tn:chartType" />
	</xs:complexType>

	<xs:complexType name="columnSetElement">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="columnSeries" type="tn:columnSeriesElement"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="type" type="tn:chartType" />
	</xs:complexType>

	<xs:complexType name="lineSeriesElement">
		<xs:complexContent>
			<xs:extension base="tn:seriesElement">
				<xs:attribute type="xs:string" name="lineColor" />
				<xs:attribute type="xs:float" name="lineAlpha" />
				<xs:attribute type="xs:float" name="lineWidth" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="lineSetElement">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="lineSeries" type="tn:lineSeriesElement"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="type" type="tn:chartType" />
	</xs:complexType>

	<xs:complexType name="axisSetElement">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element minOccurs="1" maxOccurs="unbounded" name="axis" type="tn:axisElement" />
		</xs:sequence>
	</xs:complexType>

  	<xs:complexType name="axisElement">
		<xs:attribute type="xs:string" name="id" />
		<xs:attribute type="tn:positionType" name="position" />
		<xs:attribute type="xs:string" name="categoryField" />
		<xs:attribute type="tn:fieldType" name="type" />
		<xs:attribute type="xs:string" name="title" />
		<xs:attribute type="xs:boolean" name="showTitle"  use="optional"/>
    	<xs:attribute type="xs:string" name="labelFormatter" use="optional"/>
	</xs:complexType>

	<xs:complexType name="formatterSetElement">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="formatter" type="tn:formatterElement" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="formatterElement">
		<xs:attribute type="xs:string" name="id" />
		<xs:attribute type="tn:fieldType" name="type" />
		<xs:attribute type="xs:byte" name="maxFractionalDigits" />
		<xs:attribute type="xs:long" name="abbreviationThreshold">
			<xs:annotation>
				<xs:documentation>
					Number of digits that are needed before the number will be abbreviated
					0 -> no abbreviation

					50 -> 50
					500 -> 500
					5000 -> 5,000
					50000 -> 50,000
					100000 -> 100.0k
					5000000 -> 5.0m
					5000000000 -> 5.0b
					-5000000 -> -5.0m
			</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:byte" name="abbreviationFractionalDigits" default="1" >
			<xs:annotation>
				<xs:documentation>
					Number of fractional digits to show for abbreviated values
			</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
  
	<xs:complexType name="XYChartElement">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="Service" type="tn:ServiceElement" minOccurs="1" maxOccurs="1" />
			<xs:element name="seriesSet" type="tn:seriesSetElement" minOccurs="1" maxOccurs="1" />
			<xs:element name="axisSet" type="tn:axisSetElement" minOccurs="1" maxOccurs="1" />
			<xs:element name="formatterSet" type="tn:formatterSetElement" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		
		<xs:attribute name="locale" type="xs:string" default="en_US" />
		<xs:attribute name="name" type="xs:string" />
      	<xs:attribute name="height" type="xs:short" />
      	<xs:attribute name="width" type="xs:short" />
		<xs:attribute name="sliderField" type="xs:string" />
	</xs:complexType>

	<xs:element name="XYChart" type="tn:XYChartElement" />
    
</xs:schema>

=== puneetsom/DashboardSRV/WebContent/WEB-INF/xml/RevReportTrendChart.xml
<?xml version="1.0" encoding="UTF-8"?>
<XYChart xmlns="http://www.amdocs.com/dashboard/mobile/XYChart"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://www.amdocs.com/dashboard/mobile/XYChart ../xsd/XYChart.xsd"
		 locale="en_US"
         name="Monthly Trend"
         sliderField="kpi_date_lbl">

	<Service name="selectTrendChartData" serviceCode="RevReport_selectYOYChartData" cacheLife="21600">
		<Param name="report_type" /> <!-- M (monthly), W (weekly), or D (daily) -->
		<Param name="data_field" />  <!-- hndl_cnt, asgn_cnt, sold_amt, etc -->
		<!-- <Param name="prd_year" required="false" /> -->
		<Param name="rep_id" type="number" required="false" />
		<Param name="sales_mgr_id" type="number" required="false" />
		<!-- <Param name="gm_id" type="number" required="false" /> -->
		<!-- <Param name="region_code" type="number" required="false" /> -->
		<Param name="campaign_code" required="false" />
		<Param name="channel_code" required="false" />
		<Param name="office_code" required="false" />
	</Service>

	<seriesSet type="area">
		<lineSeries id="totalAmt" displayName="Total Amount" yField="kpi_val" lineColor="1387c0" lineAlpha="1.0" lineWidth="1.5" fillColor="1387c0" fillAlpha="0.3" />
	</seriesSet>

	<axisSet>
		<axis id="xAxis" position="bottom" categoryField="kpi_date_lbl" type="string" title="Month" showTitle="false" />
		<axis id="yAxis" position="left" type="number" labelFormatter="currencyFormatter" title="Dollars ($)" showTitle="false" />
	</axisSet>
	
	<formatterSet>
		<formatter id="currencyFormatter" type="currency" maxFractionalDigits="0" abbreviationThreshold="10000" abbreviationFractionalDigits="1" />
		<formatter id="popoverFormatter" type="currency" maxFractionalDigits="0" />
		<formatter id="currencyPopoverFormatter" type="currency" maxFractionalDigits="0" />
	</formatterSet>  
  
</XYChart>

=== puneetsom/DashboardSRV/WebContent/WEB-INF/xml/ABRKpiYOYChart.xml
<?xml version="1.0" encoding="UTF-8"?>
<XYChart xmlns="http://www.amdocs.com/dashboard/mobile/XYChart"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://www.amdocs.com/dashboard/mobile/XYChart ../xsd/XYChart.xsd"
		 locale="en_US"
         name="Year-Over-Year Comparison">

	<Service name="selectYOYChartData" serviceCode="ABRKPI_selectYOYChartData" cacheLife="21600">
		<Param name="report_type" /> <!-- X (monthly), W (weekly) -->
		<Param name="data_field" />  <!-- hndl_cnt, asgn_cnt, sold_amt, etc -->
		<Param name="prd_year" required="false" />
		<Param name="branch_code" required="false" />
		<Param name="rvp_code" required="false" />
		<Param name="channel" required="false" />
		<Param name="region" required="false" />
	</Service>

	<seriesSet>
		<columnSet type="clustered">
			<columnSeries id="prevKpiVal" displayName="2012" yField="prev_kpi_val" fillColor="38b4d3" fillAlpha="0.7" />
			<columnSeries id="kpiVal" displayName="2013" yField="kpi_val" fillColor="b0d6f1" fillAlpha="0.7" />
		</columnSet>
	</seriesSet>

	<axisSet>
		<axis id="xAxis" position="bottom" categoryField="kpi_date_lbl" type="string" title="Month" showTitle="false" />
		<axis id="yAxis" position="left" type="number" labelFormatter="currencyFormatter" title="Value" showTitle="false" />
	</axisSet>
	
	<formatterSet>
		<formatter id="currencyFormatter" type="currency" maxFractionalDigits="0" abbreviationThreshold="10000" abbreviationFractionalDigits="1" />
		<formatter id="popoverFormatter" type="currency" maxFractionalDigits="0" />
		<formatter id="currencyPopoverFormatter" type="currency" maxFractionalDigits="0" />
		<formatter id="percentFormatter" type="percent" maxFractionalDigits="1" abbreviationThreshold="10000" abbreviationFractionalDigits="1" />
		<formatter id="percentPopoverFormatter" type="percent" maxFractionalDigits="0" />
	</formatterSet>  

</XYChart>

=== puneetsom/DashboardSRV/WebContent/WEB-INF/xml/SalesKpiYOYChart.xml
<?xml version="1.0" encoding="UTF-8"?>
<XYChart xmlns="http://www.amdocs.com/dashboard/mobile/XYChart"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://www.amdocs.com/dashboard/mobile/XYChart ../xsd/XYChart.xsd"
		 locale="en_US"
         name="Year-Over-Year Comparison">

	<Service name="selectYOYChartData" serviceCode="SalesKPI_selectYOYChartData" cacheLife="21600">
		<Param name="report_type" /> <!-- M (monthly), W (weekly), or D (daily) -->
		<Param name="data_field" />  <!-- hndl_cnt, asgn_cnt, sold_amt, etc -->
		<Param name="prd_year" required="false" />
		<Param name="rep_id" type="number" required="false" />
		<Param name="sales_mgr_id" type="number" required="false" />
		<Param name="gm_id" type="number" required="false" />
		<Param name="region_code" type="number" required="false" />
		<Param name="canvass_code" required="false" />
		<Param name="channel_code" required="false" />
		<Param name="office_code" required="false" />
	</Service>

	<seriesSet>
		<columnSet type="clustered">
			<columnSeries id="prevKpiVal" displayName="2012" yField="prev_kpi_val" fillColor="38b4d3" fillAlpha="0.7" />
			<columnSeries id="kpiVal" displayName="2013" yField="kpi_val" fillColor="b0d6f1" fillAlpha="0.7" />
		</columnSet>
	</seriesSet>

	<axisSet>
		<axis id="xAxis" position="bottom" categoryField="kpi_date_lbl" type="string" title="Month" showTitle="false" />
		<axis id="yAxis" position="left" type="number" labelFormatter="currencyFormatter" title="Dollars ($)" showTitle="false" />
	</axisSet>

	<formatterSet>
		<formatter id="currencyFormatter" type="currency" maxFractionalDigits="0" abbreviationThreshold="10000" abbreviationFractionalDigits="1" />
		<formatter id="popoverFormatter" type="currency" maxFractionalDigits="0" />
		<formatter id="currencyPopoverFormatter" type="currency" maxFractionalDigits="0" />
	</formatterSet>	

</XYChart>
